export const followersData = [
  {
    borderColor: "hsl(208, 92%, 53%)",
    socialIcon: "images/icon-facebook.svg",
    username: "@nathanf",
    numbers: "1987",
    text: "FOLLOWERS",
    todayIcon: "images/icon-up.svg",
    todayText: "12 Today",
    todayTextColor: "hsl(163, 72%, 41%)",
  },
  {
    borderColor: "hsl(203, 89%, 53%)",
    socialIcon: "images/icon-twitter.svg",
    username: "@nathanf",
    numbers: "1044",
    text: "FOLLOWERS",
    todayIcon: "images/icon-up.svg",
    todayText: "99 Today",
    todayTextColor: "hsl(163, 72%, 41%)",
  },
  {
    borderColor: "linear-gradient(hsl(37, 97%, 70%), hsl(329, 70%, 58%))",
    socialIcon: "images/icon-instagram.svg",
    username: "@realnathanf",
    numbers: "11k",
    text: "FOLLOWERS",
    todayIcon: "images/icon-up.svg",
    todayText: "1099 Today",
    todayTextColor: "hsl(163, 72%, 41%)",
  },
  {
    borderColor: "hsl(348, 97%, 39%)",
    socialIcon: "images/icon-youtube.svg",
    username: "@Nathan F.",
    numbers: "8249",
    text: "SUBSCRIBERS",
    todayIcon: "images/icon-down.svg",
    todayText: "144 Today",
    todayTextColor: "hsl(356, 69%, 56%)",
  },
];
